# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/casabaju?useSSL=false&serverTimezone=Europe/Madrid
spring.datasource.username=root
spring.datasource.password=admin
#spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.mvc.format.date=yyyy-MM-dd

# Puerto del servidor
server.port=8080


# Configuración del servidor SMTP (Ejemplo con Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=davidgarciasuarez999@gmail.com
spring.mail.password=aruu nwiv imzx ffiq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true